### ISSUE TITLE
Video for Slides

### ISSUE THREAD

**Issue by schneems** [kazuho/early-hints#1]
Sorry to bother you. I am a maintainer of puma/puma and i'm interested in learning more about early-hints. Do you know if there is a video that goes with these slides ? https://www.ietf.org/proceedings/97/slides/slides-97-httpbis-sessb-early-hints-00.pdf

I searched but could not find it.

**Comment by kazuho** [comment]
Hi, thank you for your interest.

I am not sure if video is available, but the discussion that happened at the venue can be found in http://etherpad.tools.ietf.org:9000/p/notes-ietf-97-httpbis?useMonospaceFont=true (line 95-102).

Also, searching for "early hints" on https://lists.w3.org/Archives/Public/ietf-http-wg/ will give you links to the discussion on the mailing list.

**Comment by kazuho** [comment]
PS. and the draft has moved to https://github.com/httpwg/http-extensions now that it has been promoted to a working group draft :D

**Comment by schneems** [comment]
Thank you a ton!
